const TODOAPP_NP = "TODO_APP/TODOAPP_NP";
const ALL_TODOS = "TODO_APP/ALL_TODOS";
const ACTIVE_TODO = "TODO_APP/ACTIVE_TODO";
const COMPLETED_TODOS = "TODO_APP/COMPLETED_TODOS";


export {
	TODOAPP_NP,
	ALL_TODOS,
	ACTIVE_TODO,
	COMPLETED_TODOS
}
